spring:
  profiles:
    active: development
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/boxfish?useUnicode=true&characterEncoding=utf8
     username: root
     password: boxfish123
  data:
    mongodb:
      host: localhost
      database: book
      username: bookRoot
      password: 123456
      authentication-database: book

mongodb:
  server:
    host: 127.0.0.1
    port: 27017

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boxfish?useUnicode=true&characterEncoding=utf8
    username: root
    password: boxfish123
#  data:
#      mongodb:
#        host: 127.0.0.1
#        database: book
#        username: bookRoot
#        password: 123456
#        authentication-database: book

---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boxfish?useUnicode=true&characterEncoding=utf8
    username: root
    password: boxfish123
  data:
      mongodb:
        host: 127.0.0.1
        database: book
        username: bookRoot
        password: 123456
        authentication-database: book